import { SafeAreaView } from "react-native-safe-area-context";
import { StyleSheet } from "react-native";

const listLandFormStyles = StyleSheet.create({
    outerContainer: {
        flex: 1,
        backgroundColor: "#f1f5f9"},
    container: {
        flex: 1,
        backgroundColor: "#f1f5f9"},
    scrollContent: {
        padding: 20,
        paddingBottom: 40},
    header: {
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "space-between",
        paddingHorizontal: 20,
        paddingVertical: 14,
        backgroundColor: "#ffffff",
        borderBottomWidth: 1,
        borderBottomColor: "#cbd5e1"},
    headerTitle: {
        fontSize: 18,
        fontWeight: "700",
        color: "#1e293b"},
    headerSubtitle: {
        fontSize: 12,
        color: "#64748b",
        marginTop: 2},
    backBtn: {
        padding: 8},
    backBtnText: {
        fontSize: 20,
        color: "#2563eb"},

    /* Step indicator */
    stepIndicator: {
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "center",
        paddingVertical: 16,
        gap: 8},
    stepDot: {
        width: 10,
        height: 10,
        borderRadius: 5,
        backgroundColor: "#e2e8f0"},
    stepDotActive: {
        backgroundColor: "#2563eb",
        width: 24,
        borderRadius: 5},
    stepDotDone: {
        backgroundColor: "#22c55e"},
    stepLabel: {
        fontSize: 14,
        color: "#64748b",
        textAlign: "center",
        marginTop: 4},

    /* Section */
    section: {
        backgroundColor: "#ffffff",
        borderRadius: 16,
        padding: 20,
        marginBottom: 16,
        borderWidth: 1,
        borderColor: "#e2e8f0",
        shadowColor: "#94a3b8",
        shadowOpacity: 0.1,
        shadowRadius: 10,
        shadowOffset: { width: 0, height: 4 },
        elevation: 2,
        borderLeftWidth: 4,
        borderLeftColor: "#3b82f6"},
    sectionTitle: {
        fontSize: 16,
        fontWeight: "700",
        color: "#1e293b",
        marginBottom: 12},
    sectionDesc: {
        fontSize: 13,
        color: "#64748b",
        marginBottom: 16,
        lineHeight: 18},

    /* Input */
    inputGroup: {
        marginBottom: 14},
    inputLabel: {
        fontSize: 13,
        fontWeight: "600",
        color: "#334155",
        marginBottom: 6},
    input: {
        backgroundColor: "#f1f5f9",
        borderWidth: 1,
        borderColor: "#cbd5e1",
        borderRadius: 10,
        paddingHorizontal: 14,
        paddingVertical: 12,
        color: "#1e293b",
        fontSize: 15},
    textArea: {
        height: 80,
        textAlignVertical: "top"},

    /* Toggle row */
    toggleRow: {
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "space-between",
        paddingVertical: 10},
    toggleLabel: {
        fontSize: 14,
        color: "#1e293b"},
    toggleBtn: {
        width: 48,
        height: 28,
        borderRadius: 14,
        backgroundColor: "#cbd5e1",
        justifyContent: "center",
        paddingHorizontal: 3},
    toggleBtnActive: {
        backgroundColor: "#22c55e"},
    toggleCircle: {
        width: 22,
        height: 22,
        borderRadius: 11,
        backgroundColor: "#fff"},
    toggleCircleActive: {
        alignSelf: "flex-end"},

    /* Picker / Pill selector */
    pillRow: {
        flexDirection: "row",
        flexWrap: "wrap",
        gap: 8},
    pill: {
        paddingHorizontal: 14,
        paddingVertical: 8,
        borderRadius: 20,
        backgroundColor: "#f1f5f9",
        borderWidth: 1,
        borderColor: "#cbd5e1"},
    pillActive: {
        backgroundColor: "#dbeafe",
        borderColor: "#2563eb"},
    pillText: {
        fontSize: 13,
        color: "#64748b",
        fontWeight: "500"},
    pillTextActive: {
        color: "#1e293b"},

    /* Validation result */
    validationBox: {
        flexDirection: "row",
        alignItems: "center",
        padding: 14,
        borderRadius: 12,
        gap: 10},
    validationBoxOk: {
        backgroundColor: "rgba(34, 197, 94, 0.1)",
        borderWidth: 1,
        borderColor: "rgba(34, 197, 94, 0.3)"},
    validationBoxFail: {
        backgroundColor: "rgba(239, 68, 68, 0.1)",
        borderWidth: 1,
        borderColor: "rgba(239, 68, 68, 0.3)"},
    validationIcon: {
        fontSize: 22},
    validationText: {
        flex: 1,
        fontSize: 13,
        color: "#1e293b",
        lineHeight: 18},

    /* Analysis results */
    analysisStat: {
        flexDirection: "row",
        justifyContent: "space-between",
        paddingVertical: 8,
        borderBottomWidth: 1,
        borderBottomColor: "#ffffff"},
    analysisStatLabel: {
        fontSize: 13,
        color: "#64748b"},
    analysisStatValue: {
        fontSize: 13,
        fontWeight: "600",
        color: "#1e293b"},

    /* Buttons */
    btnPrimary: {
        backgroundColor: "#2563eb",
        paddingVertical: 14,
        borderRadius: 12,
        alignItems: "center",
        marginTop: 12},
    btnPrimaryDisabled: {
        backgroundColor: "#93c5fd",
        opacity: 0.6},
    btnPrimaryText: {
        color: "#fff",
        fontSize: 16,
        fontWeight: "700"},
    btnSecondary: {
        backgroundColor: "transparent",
        paddingVertical: 14,
        borderRadius: 12,
        alignItems: "center",
        marginTop: 8,
        borderWidth: 1,
        borderColor: "#cbd5e1"},
    btnSecondaryText: {
        color: "#64748b",
        fontSize: 14,
        fontWeight: "600"},

    /* Navigation */
    navRow: {
        flexDirection: "row",
        justifyContent: "space-between",
        gap: 12,
        marginTop: 16},
    navBtn: {
        flex: 1,
        paddingVertical: 14,
        borderRadius: 12,
        alignItems: "center"},
    navBtnBack: {
        backgroundColor: "#ffffff",
        borderWidth: 1,
        borderColor: "#cbd5e1"},
    navBtnNext: {
        backgroundColor: "#2563eb"},
    navBtnText: {
        fontSize: 14,
        fontWeight: "600",
        color: "#1e293b"},

    /* Photos & Docs */
    cardGroup: {
        backgroundColor: "#f1f5f9",
        borderRadius: 12,
        padding: 16,
        borderWidth: 1,
        borderColor: "#cbd5e1",
        marginBottom: 16},
    rowBetween: {
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "space-between"},
    badgeRequired: {
        fontSize: 10,
        fontWeight: "700",
        color: "#ef4444",
        backgroundColor: "rgba(239, 68, 68, 0.1)",
        paddingHorizontal: 6,
        paddingVertical: 2,
        borderRadius: 4,
        textTransform: "uppercase"},
    badgeOptional: {
        fontSize: 10,
        fontWeight: "700",
        color: "#64748b",
        backgroundColor: "#ffffff",
        paddingHorizontal: 6,
        paddingVertical: 2,
        borderRadius: 4,
        textTransform: "uppercase"},
    helperText: {
        fontSize: 12,
        color: "#64748b",
        marginBottom: 12,
        lineHeight: 16},
    btnOutline: {
        borderWidth: 1,
        borderColor: "#cbd5e1",
        borderRadius: 8,
        paddingVertical: 10,
        alignItems: "center",
        flexDirection: "row",
        justifyContent: "center",
        borderStyle: "dashed",
        marginBottom: 12},
    btnOutlineText: {
        color: "#334155",
        fontSize: 14,
        fontWeight: "500",
        marginLeft: 8},
    mediaGrid: {
        flexDirection: "row",
        flexWrap: "wrap",
        gap: 8},
    imageThumbContainer: {
        width: 80,
        height: 80,
        borderRadius: 8,
        overflow: "visible"},
    imageThumb: {
        width: 80,
        height: 80,
        borderRadius: 8,
        borderWidth: 1,
        borderColor: "#cbd5e1"},
    primaryBadge: {
        position: "absolute",
        top: -4,
        left: -4,
        backgroundColor: "#ffffff",
        borderRadius: 12,
        width: 20,
        height: 20,
        alignItems: "center",
        justifyContent: "center",
        borderWidth: 1,
        borderColor: "#eab308"},
    primaryBadgeText: {
        fontSize: 10},
    removeBtn: {
        position: "absolute",
        top: -6,
        right: -6,
        backgroundColor: "#ef4444",
        width: 20,
        height: 20,
        borderRadius: 10,
        alignItems: "center",
        justifyContent: "center",
        borderWidth: 1,
        borderColor: "#f1f5f9"},
    removeBtnText: {
        color: "#fff",
        fontSize: 10,
        fontWeight: "bold"},
    errorText: {
        color: "#ef4444",
        fontSize: 12,
        marginTop: 8},
    divider: {
        height: 1,
        backgroundColor: "#e2e8f0",
        marginVertical: 4},
    docList: {
        gap: 8},
    docItem: {
        flexDirection: "row",
        alignItems: "center",
        backgroundColor: "#ffffff",
        padding: 10,
        borderRadius: 8,
        borderWidth: 1,
        borderColor: "#cbd5e1"},
    docIcon: {
        fontSize: 18,
        marginRight: 8},
    docName: {
        flex: 1,
        color: "#1e293b",
        fontSize: 13},
    docRemove: {
        padding: 4},
    docRemoveText: {
        color: "#ef4444",
        fontSize: 14,
        fontWeight: "bold"},

    /* Success screen */
    successContainer: {
        alignItems: "center",
        paddingVertical: 32},
    successIcon: {
        fontSize: 64,
        marginBottom: 16},
    successTitle: {
        fontSize: 22,
        fontWeight: "700",
        color: "#22c55e",
        marginBottom: 8},
    successSubtitle: {
        fontSize: 14,
        color: "#64748b",
        textAlign: "center",
        marginBottom: 24,
        lineHeight: 20},
    verificationCodeBox: {
        backgroundColor: "#f1f5f9",
        paddingHorizontal: 24,
        paddingVertical: 16,
        borderRadius: 12,
        borderWidth: 2,
        borderColor: "#22c55e",
        marginBottom: 24},
    verificationCodeLabel: {
        fontSize: 11,
        color: "#64748b",
        textAlign: "center",
        marginBottom: 4},
    verificationCode: {
        fontSize: 24,
        fontWeight: "800",
        color: "#22c55e",
        textAlign: "center",
        letterSpacing: 1.5}});

export default listLandFormStyles;
