export const en = {
  // ── Common ──────────────────────────────────────────────────────────────
  back: "Back",
  save: "Save",
  cancel: "Cancel",
  loading: "Loading...",
  error: "Error",
  success: "Success",
  goBackRole: "Go back to Role Selector",
  switchRole: "Go back to Role Selector",
  yes: "Yes",
  no: "No",
  confirm: "Confirm",
  remove: "Remove",
  edit: "Edit",
  delete: "Delete",
  search: "Search",
  apply: "Apply Changes",

  // ── Theme ────────────────────────────────────────────────────────────────
  lightMode: "Light Mode",
  darkMode: "Dark Mode",
  themePreference: "Theme Preference",
  themeDesc: "Toggle between light and dark display",

  // ── Role Selector ────────────────────────────────────────────────────────
  roleTitle: "Select Your Portal",
  farmerRole: "Farmer Command",
  customerRole: "Customer Market",
  roleSubtitle: "Welcome to your one-stop in grabbing and selling the world's finest spices! Select your role to continue.",
  customerDesc: "Browse the market, buy fresh spices natively.",
  farmerDesc: "Manage stock, predict profits, list your spices.",

  // ── Customer Home ─────────────────────────────────────────────────────────
  welcomeBack: "Welcome Back",
  smartAgri: "Smart Agri Suite",
  customerPortal: "Customer Portal",
  networkActive: "Market Live",
  quickGuide: "How It Works",
  guideStep1: "Set your location hub in Profile to see regional pricing.",
  guideStep2: "Browse the Marketplace and add spices to your cart.",
  guideStep3: "Track your order in real-time from dispatch to delivery.",
  quickAccess: "Quick Access",

  // ── Customer Navigation ──────────────────────────────────────────────────
  marketplace: "Marketplace",
  myOrders: "My Orders",
  profile: "Profile",
  aiPricing: "Model-powered regional pricing",
  logisticsTracking: "Real-time logistics & tracking",
  warehouseSettings: "Location hub & preferences",
  home: "Home",
  explore: "Explore",
  cart: "Cart",

  // ── Marketplace ───────────────────────────────────────────────────────────
  sourcingFrom: "Sourcing from",
  searchVariety: "Search by variety or name...",
  allSpices: "All",
  addToCart: "Add to Cart",
  checkout: "Checkout",
  tracking: "Order Tracking",
  logisticsHub: "Logistics Hub",
  noListings: "No listings found",
  noListingsSub: "There are no spices matching your filters right now.",
  inStock: "In Stock",
  perKg: "/ kg",
  qty: "Qty",
  unit: "Unit",

  // ── Cart ─────────────────────────────────────────────────────────────────
  yourCart: "Your Cart",
  cartEmpty: "Your cart is empty",
  cartEmptySub: "Browse the marketplace and add some spices.",
  placeOrder: "Place Order",
  total: "Total",
  subtotal: "Subtotal",
  transport: "Transport",
  items: "items",

  // ── Customer Orders ───────────────────────────────────────────────────────
  trackShipments: "Track your spice shipments in real-time",
  noOrdersYet: "No orders yet",
  noOrdersSub: "Browse the marketplace and confirm a purchase to see your orders here.",
  goToMarketplace: "Go to Marketplace",
  awaitingFarmer: "Awaiting Farmer",
  accepted: "Accepted",
  rejected: "Rejected",
  onTheWay: "On the Way",
  delivered: "Delivered",
  quantity: "Quantity",
  totalPaid: "Total Paid",
  transportLabel: "Transport",
  trackLiveRoute: "Track Live Route",
  rejectedByCopy: "Rejected by farmer. Please contact for details.",

  // ── Customer Profile ──────────────────────────────────────────────────────
  accountSetup: "Account Setup",
  currentLocation: "Current Location",
  fullName: "Full Name",
  emailAddress: "Email Address",
  yourName: "Your Name",
  emailPlaceholder: "email@example.com",
  languagePreferences: "Language Preferences",
  appLanguage: "App Language",
  langDesc: "Select between English and Sinhala",
  logisticsDropOff: "Logistics Drop-off Point",
  identifyDelivery: "Identify your delivery point. We've mapped all",
  activeFarmerPods: "active farmer pods across Sri Lanka for you.",
  locationSaved: "Location successfully picked! You can tap to update again at any time.",

  // ── Farmer Portal ─────────────────────────────────────────────────────────
  agriCommand: "Agri-Command",
  harvestStock: "Harvest Stock",
  inboundOrders: "Inbound Orders",
  hubLocation: "Hub Location",
  nearbyPartners: "Nearby Partners",
  modelPrice: "Trained Model Price",
  moistureLevel: "Moisture Content (%)",
  publishHarvest: "Publish Harvest",
  myHarvests: "My Harvests",
  globalFeed: "Global Feed",
  yieldPredictor: "Yield Predictor",
  regionalOpportunity: "Regional Opportunity Index",
  welcome: "Welcome",
  operationalDashboard: "Operational Dashboard",
  centralIntelligenceHub: "Central Intelligence Hub",
  networkSynced: "NETWORK SYNCED",
  revenue: "Revenue",
  profit: "Profit",
  active: "Active",
  pending: "Pending",
  globalModelPredictions: "Global Model Predictions",
  priceMomentum: "Price Momentum",
  operationalTools: "Operational Tools",
  demandMap: "Demand Map",
  demandMapDesc: "Regional spice heatmaps & tracking",
  forecaster: "Forecaster",
  forecasterDesc: "Price & Profit Prediction models",
  logistics: "Logistics",
  logisticsDesc: "Optimized route & mode analysis",
  marketplaceDesc: "Sell harvests to global clients",

  // ── Farmer Stock ──────────────────────────────────────────────────────────
  harvestInventory: "Harvest Inventory",
  manageListings: "Manage your spice marketplace listings",
  myHarvestsTab: "My Harvests",
  marketWatch: "Market Watch",
  noHarvestsListed: "No Harvests Listed",
  noHarvestsSub: "Tap the + button to list your first harvest.",
  noMarketActivity: "No Market Activity",
  noMarketSub: "There are no other farmers selling at the moment.",
  setupHubFirst: "Setup Hub First",
  setupHubSub: "Complete your profile and location to list harvests on the marketplace.",
  setupProfile: "Setup Profile",
  editListing: "Edit Listing",
  publishNewHarvest: "Publish New Harvest",
  selectSpiceType: "Select Spice Type",
  quantityKg: "Quantity (kg)",
  varietyGrade: "Variety/Grade",
  moistureContent: "Moisture Content (%)",
  predictedMarketPrice: "Predicted Market Price",
  aiLive: "MODEL LIVE",
  saveChanges: "Save Changes",
  confirmPublish: "Confirm & Publish",
  stockLevel: "Stock Level",
  pricePerKg: "Price / kg",
  reservedInCarts: "kg reserved in carts",

  // ── Farmer Orders ─────────────────────────────────────────────────────────
  inboundOrdersTitle: "Inbound Orders",
  manageFullfilments: "Manage marketplace fulfillments",
  pendingBadge: "PENDING",
  awaitingDecision: "Awaiting Decision",
  inTransit: "In Transit",
  netProceeds: "Net Proceeds",
  vehicle: "Vehicle",
  rejectOrder: "Reject",
  acceptOrder: "Accept Order",
  handOverTransport: "Hand Over to Transport",
  viewLiveRoute: "View Live Route",
  noOrdersTitle: "No Orders Yet",
  noOrdersFarmerSub: "Active customer orders will appear here for your approval.",

  // ── Farmer Profile ────────────────────────────────────────────────────────
  agriHubProfile: "Agri-Hub Profile",
  phoneNumber: "Phone Number",
  primarySpecialty: "Primary Specialty",
  globalNetworkMap: "Global Network Map",
  selectHubSeePartners: "Select your location hub and see partners",
  confirmProfileLocation: "Confirm Profile & Location",
  missingInfo: "Missing Info",
  missingInfoDesc: "Please provide your name and phone number for the marketplace.",
  profileUpdated: "Operational Hub and Profile updated successfully!",
  yourListingHub: "Your Listing Hub",
  selected: "Selected",

  // ── Simulator / Price Predictor ───────────────────────────────────────────
  pricePredictor: "Price Predictor",
  liveModel: "Live Model",
  localEstimate: "Local Estimate",
  harvestQualityMatrix: "Harvest & Quality Matrix",
  targetRegion: "Target Region",
  harvestVolume: "Harvest Volume (kg)",
  moistureLevelPct: "Moisture Level (%)",
  optimalMoisture: "Optimal moisture",
  acceptableMoisture: "Acceptable moisture",
  highMoistureWarning: "High moisture reduces price",
  projectedNetProfit: "Projected Net Profit",
  unitPrice: "Unit Price",
  volume: "Volume",
  yieldGrade: "Yield Grade",
  marginOn: "margin on",
  dryingOpportunity: "Drying Opportunity",
  dryingDesc1: "Reducing moisture from",
  dryingDesc2: "to",
  dryingDesc3: "could increase your sale price by an estimated",
  queryingPrices: "Querying regional prices...",
  modelPredictedPrices: "Model-predicted prices across all farming hubs for",

  // ── Transport ─────────────────────────────────────────────────────────────
  transportTitle: "Transport Optimizer",
  transportSub: "Find the best route and vehicle for your cargo",

  // ── Tracking ──────────────────────────────────────────────────────────────
  trackingTitle: "Live Tracking",
  trackingSub: "Your shipment is on the move",

  // ── Units ─────────────────────────────────────────────────────────────────
  kg: "kg",
  lkr: "LKR",
  g: "g",
  mg: "mg",
};

export type TranslationKey = keyof typeof en;
