export const si: Record<string, string> = {
  // ── Common ──────────────────────────────────────────────────────────────
  back: "ආපසු",
  save: "සුරකින්න",
  cancel: "අවලංගු කරන්න",
  loading: "පූරණය වෙමින්...",
  error: "දෝෂයකි",
  success: "සාර්ථකයි",
  goBackRole: "කාර්ය භාරය තේරීමට ආපසු යන්න",
  switchRole: "කාර්ය භාරය තේරීමට ආපසු යන්න",
  yes: "ඔව්",
  no: "නැත",
  confirm: "තහවුරු කරන්න",
  remove: "ඉවත් කරන්න",
  edit: "සංස්කරණය කරන්න",
  delete: "මකන්න",
  search: "සොයන්න",
  apply: "වෙනස්කම් යොදන්න",

  // ── Theme ────────────────────────────────────────────────────────────────
  lightMode: "දීප්ත මාදිලිය",
  darkMode: "අඳුරු මාදිලිය",
  themePreference: "තේමා මනාපය",
  themeDesc: "ආලෝකමත් සහ අඳුරු දර්ශනය අතර මාරු වන්න",

  // ── Role Selector ────────────────────────────────────────────────────────
  roleTitle: "ඇතුල්වන දොරටුව තෝරන්න",
  farmerRole: "ගොවි පාලන මැදිරිය",
  customerRole: "පාරිභෝගික වෙළඳපොළ",
  roleSubtitle: "ලොව හොඳම කුළුබඩු ගැනීමට සහ විකිණීමට ඔබේ භූමිකාව තෝරන්න.",
  customerDesc: "වෙළඳපොළ 둘러보고 නැවුම් කුළුබඩු ගන්න.",
  farmerDesc: "තොගය කළමනාකරණය කරන්න, ලාභ පුරෝකථනය කරන්න.",

  // ── Customer Home ─────────────────────────────────────────────────────────
  welcomeBack: "නැවත ආයුබෝවන්",
  smartAgri: "ස්මාර්ට් කෘෂි",
  customerPortal: "පාරිභෝගික මුලපිරීම",
  networkActive: "වෙළඳපොළ සජීවීව",
  quickGuide: "ක්‍රියා කරන ආකාරය",
  guideStep1: "ප්‍රාදේශීය මිල ගනන් දැකීමට ඔබේ ස්ථානය සකසන්න.",
  guideStep2: "වෙළඳපොළ 둘러보고 කූඩයට කුළුබඩු එකතු කරන්න.",
  guideStep3: "ඔබේ ඇණවුම රථය සිට ගෙදර දක්වා ලුහුබැඳීම් කරන්න.",
  quickAccess: "ඉක්මන් ප්‍රවේශය",

  // ── Customer Navigation ──────────────────────────────────────────────────
  marketplace: "වෙළඳපොළ",
  myOrders: "මගේ ඇණවුම්",
  profile: "පැතිකඩ",
  aiPricing: "ආදර්ශ-ක්‍රමයෙන් ප්‍රාදේශීය මිලකරණය",
  logisticsTracking: "සැබෑ කාල රථ ලුහුබැඳීම",
  warehouseSettings: "ස්ථාන කේන්ද්‍රය සහ මනාපයන්",
  home: "නිවස",
  explore: "ගවේෂණය",
  cart: "කූඩය",

  // ── Marketplace ───────────────────────────────────────────────────────────
  sourcingFrom: "සම්පත් ලබාගන්නේ",
  searchVariety: "වර්ගය හෝ නම සොයන්න...",
  allSpices: "සියල්ල",
  addToCart: "කූඩයට එක් කරන්න",
  checkout: "මිලදී ගන්න",
  tracking: "ඇණවුම් ලුහුබැඳීම",
  logisticsHub: "ප්‍රවාහන මධ්‍යස්ථානය",
  noListings: "ලැයිස්තු හමු නොවිණි",
  noListingsSub: "ඔබේ පෙරහන්වලට ගැළපෙන කුළුබඩු නොමැත.",
  inStock: "තොගයේ ඇත",
  perKg: "/ කිලෝ",
  qty: "ප්‍රමාණය",
  unit: "ඒකකය",

  // ── Cart ─────────────────────────────────────────────────────────────────
  yourCart: "ඔබේ කූඩය",
  cartEmpty: "ඔබේ කූඩය හිස්ය",
  cartEmptySub: "වෙළඳපොළ 둘러보고 කුළුබඩු එකතු කරන්න.",
  placeOrder: "ඇණවුම් කරන්න",
  total: "මුළු",
  subtotal: "උප මුළු",
  transport: "ප්‍රවාහන",
  items: "අයිතම",

  // ── Customer Orders ───────────────────────────────────────────────────────
  trackShipments: "ඔබේ කුළුබඩු නැව්ගත කිරීම් සැබෑ කාලයේදී ලුහුබඳින්න",
  noOrdersYet: "ඇණවුම් නොමැත",
  noOrdersSub: "ඔබේ ඇණවුම් ලෙස නැව්ගත කිරීම් ලෙස බැලීමට වෙළඳපොළ 둘러보න්න.",
  goToMarketplace: "වෙළඳපොළට යන්න",
  awaitingFarmer: "ගොවිතැන් බලාපොරොත්තු",
  accepted: "පිළිගත්",
  rejected: "ප්‍රතික්ෂේපිත",
  onTheWay: "ගමනේදී",
  delivered: "ලැබිණි",
  quantity: "ප්‍රමාණය",
  totalPaid: "මුළු ගෙවූ",
  transportLabel: "ප්‍රවාහනය",
  trackLiveRoute: "සජීවී මාර්ගය ලුහුබැඳීම",
  rejectedByCopy: "ගොවිතැන් ප්‍රතික්ෂේප කළේය. විස්තර සඳහා සම්බන්ධ වන්න.",

  // ── Customer Profile ──────────────────────────────────────────────────────
  accountSetup: "ගිණුම් සැකසුම",
  currentLocation: "වත්මන් ස්ථානය",
  fullName: "සම්පූර්ண නම",
  emailAddress: "ඊමේල් ලිපිනය",
  yourName: "ඔබේ නම",
  emailPlaceholder: "email@example.com",
  languagePreferences: "භාෂා මනාපය",
  appLanguage: "යෙදුම් භාෂාව",
  langDesc: "ඉංග්‍රීසි සහ සිංහල අතර තෝරන්න",
  logisticsDropOff: "ප්‍රවාහන ලැබීමේ ස්ථානය",
  identifyDelivery: "ඔබේ ලබාදීමේ ස්ථානය හඳුනාගන්න. අපි සිතියම්ගත කළෙමු",
  activeFarmerPods: "ශ්‍රී ලංකාව පුරා ගොවිතැන් ස්ථාන.",
  locationSaved: "ස්ථානය සාර්ථකව තෝරාගෙන ඇත! ඕනෑම වේලාවක නැවත යාවත්කාලීන කළ හැකිය.",

  // ── Farmer Portal ─────────────────────────────────────────────────────────
  agriCommand: "කෘෂි-විධානය",
  harvestStock: "අස්වැන්න තොගය",
  inboundOrders: "ලැබෙන ඇණවුම්",
  hubLocation: "කේන්ද්‍රස්ථානය",
  nearbyPartners: "ආසන්න හවුල්කරුවන්",
  modelPrice: "ආදර්ශ පුරෝකථන මිල",
  moistureLevel: "තෙතමනය (%)",
  publishHarvest: "වෙළඳපොළට ඇතුලත් කරන්න",
  myHarvests: "මගේ අස්වැන්න",
  globalFeed: "පොදු වෙළඳපොළ",
  yieldPredictor: "අස්වැන්න පුරෝකථනය",
  regionalOpportunity: "ප්‍රාදේශීය අවස්ථා දර්ශකය",
  welcome: "ආයුබෝවන්",
  operationalDashboard: "මෙහෙයුම් උපකරණ පෙළ",
  centralIntelligenceHub: "කේන්ද්‍රීය බුද්ධිමත් මධ්‍යස්ථානය",
  networkSynced: "ජාලය සමමුහුර්ත",
  revenue: "ආදායම",
  profit: "ලාභය",
  active: "සක්‍රිය",
  pending: "අනුදැනුම් බලාපොරොත්තු",
  globalModelPredictions: "ගෝලීය ආදර්ශ පුරෝකථන",
  priceMomentum: "මිල ගතිය",
  operationalTools: "මෙහෙයුම් මෙවලම්",
  demandMap: "ඉල්ලුම් සිතියම",
  demandMapDesc: "ප්‍රාදේශීය කුළුබඩු තාප සිතියම් සහ ලුහුබැඳීම",
  forecaster: "පුරෝකථකය",
  forecasterDesc: "මිල සහ ලාභ පුරෝකථන ආදර්ශ",
  logistics: "රථවාහන",
  logisticsDesc: "ප්‍රශස්ත මාර්ගය සහ ප්‍රවාහන විශ්ලේෂණය",
  marketplaceDesc: "ගෝලීය ගනුදෙනුකරුවන්ට අස්වැන්න විකිණීම",

  // ── Farmer Stock ──────────────────────────────────────────────────────────
  harvestInventory: "අස්වැන්න තොගාගාරය",
  manageListings: "ඔබේ කුළුබඩු වෙළඳ ලැයිස්තු කළමනාකරණය කරන්න",
  myHarvestsTab: "මගේ අස්වැන්න",
  marketWatch: "වෙළඳ නිරීක්ෂණය",
  noHarvestsListed: "අස්වැන්නු ලැයිස්තු නොමැත",
  noHarvestsSub: "ඔබේ පළමු අස්වැන්න ලැයිස්තු කිරීමට + බොත්තම ඔබන්න.",
  noMarketActivity: "වෙළඳ ක්‍රියාකාරකම් නොමැත",
  noMarketSub: "දැනට වෙනත් ගොවිතැන්කරුවන් විකිණීම් නොකරයි.",
  setupHubFirst: "මුලින් කේන්ද්‍රය සකසන්න",
  setupHubSub: "වෙළඳ ලැයිස්තු කිරීමට ඔබේ පැතිකඩ සහ ස්ථානය සම්පූර්ණ කරන්න.",
  setupProfile: "පැතිකඩ සකසන්න",
  editListing: "ලැයිස්තුව සංස්කරණය කරන්න",
  publishNewHarvest: "නව අස්වැන්නක් ප්‍රකාශිත කරන්න",
  selectSpiceType: "කුළුබඩු වර්ගය තෝරන්න",
  quantityKg: "ප්‍රමාණය (කිලෝ)",
  varietyGrade: "වර්ගය/ශ්‍රේණිය",
  moistureContent: "තෙතමනය (%)",
  predictedMarketPrice: "පුරෝකථිත වෙළඳ මිල",
  aiLive: "සජීවී ආදර්ශ",
  saveChanges: "වෙනස්කම් සුරකින්න",
  confirmPublish: "තහවුරු කර ප්‍රකාශිත කරන්න",
  stockLevel: "තොගයේ මට්ටම",
  pricePerKg: "කිලෝ / මිල",
  reservedInCarts: "කූඩවල රක්‍ෂිත කිලෝ",

  // ── Farmer Orders ─────────────────────────────────────────────────────────
  inboundOrdersTitle: "ලැබෙන ඇණවුම්",
  manageFullfilments: "වෙළඳ ඉෂ්ටදාම කළමනාකරණය",
  pendingBadge: "බලාපොරොත්තු",
  awaitingDecision: "තීරණය බලාගෙ",
  inTransit: "ගමනේදී",
  netProceeds: "ශුද්ධ ආදායම",
  vehicle: "වාහනය",
  rejectOrder: "ප්‍රතික්ෂේප කරන්න",
  acceptOrder: "ඇණවුම පිළිගන්න",
  handOverTransport: "ප්‍රවාහනයට භාර දෙන්න",
  viewLiveRoute: "සජීවී මාර්ගය බලන්න",
  noOrdersTitle: "ඇණවුම් නොමැත",
  noOrdersFarmerSub: "සක්‍රිය ගනුදෙනුකරු ඇණවුම් ඔබගේ අනුමැතිය සඳහා මෙහි දිස්වේ.",

  // ── Farmer Profile ────────────────────────────────────────────────────────
  agriHubProfile: "කෘෂි-කේන්ද්‍ර පැතිකඩ",
  phoneNumber: "දුරකථන අංකය",
  primarySpecialty: "ප්‍රාථමික විශේෂත්වය",
  globalNetworkMap: "ගෝලීය ජාල සිතියම",
  selectHubSeePartners: "ඔබේ ස්ථාන කේන්ද්‍රය තෝරා හවුල්කරුවන් බලන්න",
  confirmProfileLocation: "පැතිකඩ සහ ස්ථානය තහවුරු කරන්න",
  missingInfo: "තොරතුරු අඩු",
  missingInfoDesc: "කරුණාකර වෙළඳ සඳහා ඔබේ නම සහ දුරකථන අංකය ලබා දෙන්න.",
  profileUpdated: "මෙහෙයුම් කේන්ද්‍රය සහ පැතිකඩ සාර්ථකව යාවත්කාලීන කෙරිණ!",
  yourListingHub: "ඔබේ ලැයිස්තු කේන්ද්‍රය",
  selected: "තෝරාගත්",

  // ── Simulator / Price Predictor ───────────────────────────────────────────
  pricePredictor: "මිල පුරෝකථකය",
  liveModel: "සජීවී ආදර්ශය",
  localEstimate: "දේශීය ඇස්තමේන්තු",
  harvestQualityMatrix: "අස්වැන්න සහ ගුණත්ව මාතෘකාව",
  targetRegion: "ඉලක්ක ප්‍රදේශය",
  harvestVolume: "අස්වැන්නේ ප්‍රමාණය (කිලෝ)",
  moistureLevelPct: "තෙතමනය (%)",
  optimalMoisture: "ප්‍රශස්ත තෙතමනය",
  acceptableMoisture: "පිළිගත හැකි තෙතමනය",
  highMoistureWarning: "ඉහළ තෙතමනය මිල අඩු කරයි",
  projectedNetProfit: "ඇස්තමේන්තු ශුද්ධ ලාභය",
  unitPrice: "ඒකක මිල",
  volume: "ප්‍රමාණය",
  yieldGrade: "අස්වැන්නේ ශ්‍රේණිය",
  marginOn: "ලාභ අනුපාතය",
  dryingOpportunity: "වියළීමේ අවස්ථාව",
  dryingDesc1: "තෙතමනය",
  dryingDesc2: "සිට",
  dryingDesc3: "දක්වා අඩු කිරීම මිල kg එකකට ඇස්තමේන්තු",
  queryingPrices: "ප්‍රාදේශීය මිල ගනන් ලබා ගනිමින්...",
  modelPredictedPrices: "සියලු ගොවිතැන් කේන්ද්‍র සඳහා ආදර්ශ-පුරෝකථිත මිල:",

  // ── Transport ─────────────────────────────────────────────────────────────
  transportTitle: "ප්‍රවාහන ප්‍රශස්ත",
  transportSub: "ඔබේ භාණ්ඩ සඳහා හොඳම මාර්ගය සහ වාහනය සොයන්න",

  // ── Tracking ──────────────────────────────────────────────────────────────
  trackingTitle: "සජීවී ලුහුබැඳීම",
  trackingSub: "ඔබේ නැව්ගත කිරීම ගමනේ ඇත",

  // ── Units ─────────────────────────────────────────────────────────────────
  kg: "කි.ග්‍රෑ",
  lkr: "රුපියල්",
  g: "ග්‍රෑ",
  mg: "මිලිග්‍රෑ",
};
